Repository nasa/sample_app, pull requests merged in 2020-05, with the labels that each got.

#61 Fix #60, incorrect conversion specifier
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-20200429, IC-20200429, code reviewed

#54 Fix #53, Opaque CFE_SB_MsgId_t values
  fsw/src/sample_app.c
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-20200408, CCB-20200506, IC-20200429, code reviewed

#63 Integration Candidate COMBINED 2020-04-29 and 2020-05-06
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: IC-20200429
