Repository nasa/sample_app, pull requests merged in 2020-03, with the labels that each got.

#47 IC 20200304
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_msg.h
  fsw/src/sample_table.c
  fsw/src/sample_table.h
Labels: CCB - 20200311, IC - 20200304

#42 Fix #41, Do not use aux_source_directory in sample build script
  CMakeLists.txt
Labels: CCB - 20200318, IC - 20200318, code reviewed

#26 Fix #8, Add sample app tests
  CMakeLists.txt
  fsw/src/sample_app.c
  fsw/src/sample_table.c
  fsw/src/sample_table.h
  unit-test/CMakeLists.txt
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/coveragetest/sample_app_coveragetest_common.h
  unit-test/inc/ut_sample_app.h
Labels: CCB - 20200318, IC - 20200318, enhancement

#49 Integration Candidate 2020-03-18
  CMakeLists.txt
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
  fsw/src/sample_table.c
  fsw/src/sample_table.h
  unit-test/CMakeLists.txt
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/coveragetest/sample_app_coveragetest_common.h
  unit-test/inc/ut_sample_app.h
Labels: IC - 20200318
