Repository nasa/sample_app, pull requests merged in 2020-11, with the labels that each got.

#100 Fix #77, Standardize to SAMPLE_APP_ namespace prefix
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_events.h
  fsw/src/sample_app_msg.h
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/inc/ut_sample_app.h
Labels: CCB-20201028, IC-20201103, dependency

#102 Integration Candidate: 2020-11-03
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_events.h
  fsw/src/sample_app_msg.h
  fsw/src/sample_app_version.h
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/inc/ut_sample_app.h
Labels: IC-20201103

#104 Fix #103, Use MSG APIs
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_msg.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-20201104, IC-20201110

#109 Fix #105, Remove non-portable OS_PACK
  fsw/src/sample_app_msg.h
Labels: CCB-FastTrack, conflict

#108 Integration Candidate: 2020-11-10
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_msg.h
  fsw/src/sample_app_version.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: IC-20201110
