Repository nasa/sample_app, pull requests merged in 2020-08, with the labels that each got.

#86 Close #80, Add build number and baseline
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
Labels: CCB-FastTrack, IC-20200729

#85 Integration candidate 2020-07-29
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
  unit-test/CMakeLists.txt
Labels: IC-20200729

#90 Fix #89, Remove CFE_SB_InitMsg use in coverage test
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-20200826, IC-20200826, code reviewed, enhancement

#92 Fix #37, Apply style
  fsw/mission_inc/sample_app_perfids.h
  fsw/platform_inc/sample_app_msgids.h
  fsw/platform_inc/sample_app_table.h
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_events.h
  fsw/src/sample_app_msg.h
  fsw/src/sample_app_version.h
  fsw/tables/sample_app_tbl.c
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/coveragetest/sample_app_coveragetest_common.h
  unit-test/inc/ut_sample_app.h
Labels: IC-20200826, code reviewed
