Repository nasa/sample_app, pull requests merged in 2020-06, with the labels that each got.

#67 Fix #66, Add extended context information to event hook
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-20200527, IC-20200527, code reviewed, enhancement

#69 Fix #68, remove references to CCSDS types
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB-Fast Track, IC-20200527, enhancement, ready for CCB

#71 Integration Candidate: 2020-05-27
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_version.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: IC-20200527

#76 Integration Candidate: 2020-06-10
  CMakeLists.txt
  README.md
  fsw/platform_inc/sample_app_table.h
  fsw/src/sample_app.c
  fsw/src/sample_app.h
  fsw/src/sample_app_version.h
  fsw/tables/sample_app_tbl.c
  unit-test/coveragetest/coveragetest_sample_app.c
  unit-test/coveragetest/sample_app_coveragetest_common.h
Labels: IC-20200610
