Repository nasa/sample_app, pull requests merged in 2020-04, with the labels that each got.

#52 Integration Candidate 2020-03-25
  README.md
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
Labels: IC - 20200325

#59 Fix #50, Reference skeleton_app in ReadMe
  README.md
Labels: CCB - 20200422, CCB - Fast Track, IC - 20200415, code reviewed, docs

#57 Fix #56, Update coverage compile/link flag options
  unit-test/CMakeLists.txt
Labels: CCB-20200422, IC-20200422, bug, code reviewed
