Repository nasa/sample_app, pull requests merged in 2021-01, with the labels that each got.

#119 Fix #118, Create Security Policy
  SECURITY.md
Labels: CCB:FastTrack, IC:2021-01-19, docs, security

#117 Fix #101, Correct CFE_TBL_GetAddress return code check
  fsw/src/sample_app.c
Labels: CCB:FastTrack, IC:2021-01-19

#116 Fix #115, Refactor UT_ClearForceFail to UT_ClearDefaultReturnValue
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: CCB:2021-01-13, IC:2021-01-19, dependency, refactor

#121 sample_app Integration candidate: 2021-01-19
  README.md
  SECURITY.md
  fsw/src/sample_app.c
  fsw/src/sample_app_version.h
  unit-test/coveragetest/coveragetest_sample_app.c
Labels: IC:2021-01-19
